### PR TITLE
fix the golang panic issue, if the Value, BoolValue, Sum is nil

### PR DESCRIPTION
**Pull request by oldmikeyang**
In the senml struct, value, Boolvalue and Sum maybe nil.
This cause the http-adapter panic.

2017/09/02 20:26:53 http: panic serving [::1]:59220: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc420068a80)
	/usr/lib/golang/src/net/http/server.go:1491 +0x12a
panic(0x9371c0, 0xc42000c140)
	/usr/lib/golang/src/runtime/panic.go:458 +0x243
github.com/mainflux/http-adapter/api.buildMessages(0xc42001959f, 0x24, 0xc4200cc180, 0xb8, 0x0, 0x9f53c4, 0x1c, 0xc4200bd080, 0x1, 0x4, ...)
	/root/go/src/github.com/mainflux/http-adapter/api/transport.go:134 +0x430
github.com/mainflux/http-adapter/api.decodeRequest(0xc4f140, 0xc4200efd40, 0xc4200be2d0, 0x7f0d9a266000, 0x4, 0x0, 0x6)
	/root/go/src/github.com/mainflux/http-adapter/api/transport.go:69 +0x23a
github.com/mainflux/http-adapter/vendor/github.com/go-kit/kit/transport/http.Server.ServeHTTP(0xc4201803c0, 0xa26378, 0xa26388, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa26380, ...)
	/root/go/src/github.com/mainflux/http-adapter/vendor/github.com/go-kit/kit/transport/http/server.go:101 +0x188
github.com/mainflux/http-adapter/vendor/github.com/go-kit/kit/transport/http.(*Server).ServeHTTP(0xc42018c380, 0xc4e340, 0xc4200f3930, 0xc4200be2d0)
	<autogenerated>:3 +0xac
github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone.(*Route).serveMatchedRequest(0xc42018a140, 0xc4e340, 0xc4200f3930, 0xc4200be1e0, 0xc4200efd10)
	/root/go/src/github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone/helper_17.go:38 +0x10e
github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone.(*Route).parse(0xc42018a140, 0xc4e340, 0xc4200f3930, 0xc4200be1e0, 0xc420190348)
	/root/go/src/github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone/route.go:143 +0x168
github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone.(*Mux).parse(0xc420188570, 0xc4e340, 0xc4200f3930, 0xc4200be1e0, 0x9e7a18)
	/root/go/src/github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone/helper.go:18 +0xa0
github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone.(*Mux).ServeHTTP(0xc420188570, 0xc4e340, 0xc4200f3930, 0xc4200be1e0)
	/root/go/src/github.com/mainflux/http-adapter/vendor/github.com/go-zoo/bone/bone.go:43 +0x4d
net/http.serverHandler.ServeHTTP(0xc420192180, 0xc4e340, 0xc4200f3930, 0xc4200be1e0)
	/usr/lib/golang/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420068a80, 0xc4f080, 0xc4201643c0)
	/usr/lib/golang/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2293 +0x44d

### CODE REVIEW

**Comment by mijicd** [comment]
@oldmikeyang could you please provide the test sample you've been using to verify this behaviour?

Note that the service is undergoing a complete rewrite, so any feedback on noticed bugs is appreciated.

**Comment by drasko** [comment]
@oldmikeyang thanks for the PR!

A code style remark: I would prefer new code to respect formatting of existing code (space alignment in struct declaration).

**Comment by drasko** [comment]
I've tested and observed the panic. I propose that we accept the PR for now, and fix the formatting and add the test during forthcoming refactoring phase.

**Comment by drasko** [comment]
@oldmikeyang merged, thanks!

**Pull request merged**
